Repository Fermain/-mollify, pull requests merged in 2023-05, with the labels that each got.

#34 Updated layout to match most recent wireframe
  packages/lms/src/lib/components/footer/Footer.svelte
  packages/lms/src/lib/components/header/Header.svelte
  packages/lms/src/lib/components/header/Reader.svelte
  packages/lms/src/lib/components/header/Search.svelte
  packages/lms/src/lib/components/ui/Ego.svelte
  packages/lms/src/routes/+layout.svelte
Labels: enhancement

#31 Dynamic Navigation and Global Theming
  package-lock.json
  package.json
  packages/lms/package.json
  packages/lms/src/app.html
  packages/lms/src/lib/components/content/Main.svelte
  packages/lms/src/lib/components/footer/Footer.svelte
  packages/lms/src/lib/components/header/Header.svelte
  packages/lms/src/lib/components/header/Logo.svelte
  packages/lms/src/lib/components/header/Reader.svelte
  packages/lms/src/lib/components/header/Search.svelte
  packages/lms/src/lib/components/header/Settings.svelte
  packages/lms/src/lib/components/molly/Molly.svelte
  packages/lms/src/lib/components/navigation/ContentNav.svelte
  packages/lms/src/lib/components/navigation/CourseNav.svelte
  packages/lms/src/lib/components/navigation/IconNav.svelte
  packages/lms/src/lib/components/navigation/Navigation.svelte
  packages/lms/src/lib/components/navigation/ProgrammeNav.svelte
  packages/lms/src/lib/components/navigation/RecursiveNav.svelte
  packages/lms/src/lib/components/tags/Tags.svelte
  packages/lms/src/lib/components/ui/Ego.svelte
  packages/lms/src/lib/stores/files.ts
  packages/lms/src/lib/styles/_colors.scss
  packages/lms/src/lib/styles/_components.scss
  packages/lms/src/lib/styles/_global.scss
  packages/lms/src/lib/styles/_variables.scss
  packages/lms/src/lib/styles/styles.scss
  packages/lms/src/lib/utils/getCurrent.ts
  packages/lms/src/lib/utils/parseMarkdown.ts
  packages/lms/src/routes/+layout.svelte
  packages/lms/src/routes/+page.svelte
  packages/lms/src/routes/api/parseMarkdown/+server.ts
  packages/lms/src/routes/content/The Burnt Toast Institute/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Cakes And Cupcakes/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Cakes And Cupcakes/Flat and Lifeless Cupcakes/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Cakes And Cupcakes/Lopsided Cakes/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Cakes And Cupcakes/The Science of Cake Flops/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Cookies And Brownies/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Cookies And Brownies/Burnt to a Crisp/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Cookies And Brownies/Rock Hard Chewy Brownies/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Cookies And Brownies/Undercooked And Soggy/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Pies and Tarts/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Pies and Tarts/Burnt Pie Crusts/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Pies and Tarts/Leaky Tarts/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Baking Disasters/Introduction to Baking Disasters/Pies and Tarts/Overfilled and Sticky Pies/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Culinary Basics/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Culinary Basics/Cookery 101/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Culinary Basics/Cookery 101/The Basics/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Culinary Basics/Cookery 101/The Basics/Baking/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Culinary Basics/Cookery 101/The Basics/Cooking/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Culinary Basics/Cookery 101/The Basics/Gastronomy/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Culinary Basics/Cookery 101/The Recipes/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Culinary Basics/Cookery 101/The Recipes/Bread/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Culinary Basics/Cookery 101/The Recipes/Cake/+page.md
  packages/lms/src/routes/content/The Burnt Toast Institute/Culinary Basics/Cookery 101/The Recipes/Pastries/+page.md
  packages/lms/static/testmarkdown.md
  packages/lms/svelte.config.js
  packages/lms/tests/test.ts
Labels: feature

#32 Type Definitions
  .gitignore
  package-lock.json
  packages/flow/package.json
  packages/lms/package.json
  packages/molly/package.json
  packages/package.json
  packages/types/README.md
  packages/types/index.ts
  packages/types/lib/Entity.ts
  packages/types/lib/index.ts
  packages/types/package.json
  packages/types/tsconfig.json
Labels: feature

#43 Cli patch
  packages/lms/src/lib/utils/getEntityChildren.ts
  packages/lms/src/lib/utils/getEntityFrontmatter.ts
  packages/lms/src/lib/utils/getEntitySlug.ts
Labels: bug
